parameters:
    # Standardwerte für die App-Parameter
    app.test_email: '%env(string:APP_TEST_EMAIL)%'
    app.email_subject: '%env(string:APP_EMAIL_SUBJECT)%'
    app.sender_email: '%env(string:APP_SENDER_EMAIL)%'
    app.sender_name: '%env(string:APP_SENDER_NAME)%'
    app.ticket_base_url: '%env(string:APP_TICKET_BASE_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    # Explicit bindings for mailer adapters/factory
    App\Service\SymfonyMailerAdapter:
        arguments:
            $mailer: '@mailer.mailer'
        tags: []

    App\Service\SymfonyMailTransportFactory:
        tags: []
        public: false